defult_click_point:
  x: 405
  y: 518
method: ocr
picture_path: images/IsCooldown_right_cool_down.png
region:
  bottom: 530
  left: 367
  right: 443
  top: 507
swipe: null
threshold: 0.8
window_name: IsCooldown_right
