defult_click_point:
  x: 391
  y: 759
method: ocr
picture_path: images/train_cool_down_open.png
region:
  bottom: 775
  left: 348
  right: 435
  top: 744
swipe: null
threshold: 0.8
window_name: train_cool_down
