defult_click_point:
  x: 271
  y: 839
method: ocr
picture_path: images/warehouse_rewards_cool_down.png
region:
  bottom: 857
  left: 204
  right: 339
  top: 821
swipe:
  duration: 0.5
  end:
    x: 172
    y: 320
  start:
    x: 170
    y: 576
threshold: 0.8
window_name: warehouse_rewards_cool_down
