defult_click_point:
  x: 90
  y: 27
method: check
picture_path: images/alliance_Step1_window.png
region:
  bottom: 39
  left: 67
  right: 113
  top: 16
swipe: null
threshold: 0.8
window_name: alliance_Step1
