defult_click_point:
  x: 252
  y: 830
method: check
picture_path: images/alliance_Step10_window.png
region:
  bottom: 840
  left: 177
  right: 328
  top: 820
swipe: null
threshold: 0.8
window_name: alliance_Step10
