defult_click_point:
  x: 140
  y: 347
method: check
picture_path: images/alliance_Step9_window.png
region:
  bottom: 355
  left: 31
  right: 250
  top: 339
swipe: null
threshold: 0.8
window_name: alliance_Step9
