defult_click_point:
  x: 449
  y: 139
method: None
picture_path: images/alliance_Step5_open.png
region:
  bottom: 149
  left: 439
  right: 459
  top: 129
swipe: null
threshold: 0.8
window_name: alliance_Step5
