defult_click_point:
  x: 173
  y: 643
method: swipe_find
picture_path: images/AttackIceBeast_Step1_open.png
region:
  bottom: 677
  left: 129
  right: 217
  top: 610
swipe:
  duration: 310.0
  end:
    x: 343
    y: 657
  start:
    x: 244
    y: 658
threshold: 0.8
window_name: AttackIceBeast_Step1
