defult_click_point:
  x: 173
  y: 641
method: None
picture_path: images/AttackIceBeast_Step1_window.png
region:
  bottom: 685
  left: 119
  right: 227
  top: 597
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step1
