defult_click_point:
  x: 397
  y: 528
method: None
picture_path: images/click_figure_window.png
region:
  bottom: 535
  left: 374
  right: 420
  top: 521
swipe: null
threshold: 0.8
window_name: click_figure
