defult_click_point:
  x: 335
  y: 641
method: swipe_find
picture_path: images/coal_collection_Step2_open.png
region:
  bottom: 675
  left: 293
  right: 377
  top: 607
swipe:
  duration: 440.0
  end:
    x: 110
    y: 657
  start:
    x: 286
    y: 650
threshold: 0.8
window_name: coal_collection_Step2
