defult_click_point:
  x: 32
  y: 617
method: None
picture_path: images/collection_Step1_open.png
region:
  bottom: 632
  left: 18
  right: 47
  top: 602
swipe: null
threshold: 0.8
window_name: collection_Step1
