defult_click_point:
  x: 356
  y: 393
method: ocr
picture_path: images/collection_Step4_cool_down.png
region:
  bottom: 405
  left: 327
  right: 385
  top: 382
swipe: null
threshold: 0.8
window_name: collection_Step4
