defult_click_point:
  x: 384
  y: 310
method: None
picture_path: images/collection_Step6_window.png
region:
  bottom: 404
  left: 331
  right: 438
  top: 217
swipe: null
threshold: 0.8
window_name: collection_Step6
