defult_click_point:
  x: 156
  y: 529
method: ocr
picture_path: images/free_quee_6_cool_down.png
region:
  bottom: 541
  left: 123
  right: 189
  top: 518
swipe: null
threshold: 0.8
window_name: free_quee_6
