defult_click_point:
  x: 157
  y: 273
method: check
picture_path: images/free_quee_1_window.png
region:
  bottom: 280
  left: 136
  right: 178
  top: 266
swipe: null
threshold: 0.5
window_name: free_quee_1
