defult_click_point:
  x: 376
  y: 852
method: None
picture_path: images/HeroRecruit_Step2_open.png
region:
  bottom: 866
  left: 327
  right: 425
  top: 839
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step2
