defult_click_point:
  x: 30
  y: 27
method: None
picture_path: images/HeroRecruit_Step6_open.png
region:
  bottom: 48
  left: 7
  right: 54
  top: 7
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step6
