defult_click_point:
  x: 253
  y: 442
method: check
picture_path: images/Intelligence_beast_Step2_window.png
region:
  bottom: 466
  left: 169
  right: 337
  top: 418
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step2
