defult_click_point:
  x: 86
  y: 341
method: find
picture_path: images/Intelligence_beast_Step4_window.png
region:
  bottom: 355
  left: 76
  right: 96
  top: 328
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step4
