defult_click_point:
  x: 284
  y: 444
method: None
picture_path: images/spear_training_complete_window.png
region:
  bottom: 461
  left: 269
  right: 300
  top: 428
swipe: null
threshold: 0.8
window_name: spear_training_complete
