defult_click_point:
  x: 371
  y: 833
method: check
picture_path: images/train_Step2_window.png
region:
  bottom: 846
  left: 349
  right: 394
  top: 820
swipe: null
threshold: 0.8
window_name: train_Step2
