defult_click_point:
  x: 255
  y: 787
method: ocr
picture_path: images/warehouse_rewards_cool_down.png
region:
  bottom: 804
  left: 192
  right: 318
  top: 770
swipe:
  duration: 0.5
  end:
    x: 162
    y: 300
  start:
    x: 160
    y: 540
threshold: 0.8
window_name: warehouse_rewards_cool_down
