defult_click_point:
  x: 394
  y: 640
method: None
picture_path: images/wood_collection_Step2_window.png
region:
  bottom: 677
  left: 352
  right: 436
  top: 604
swipe:
  duration: 520.0
  end:
    x: 129
    y: 643
  start:
    x: 336
    y: 642
threshold: 0.8
window_name: wood_collection_Step2
