defult_click_point:
  x: 456
  y: 577
method: find
picture_path: images/alliance_Step8_open.png
region:
  bottom: 598
  left: 404
  right: 509
  top: 557
swipe: null
threshold: 0.8
window_name: alliance_Step8
