defult_click_point:
  x: 96
  y: 29
method: check
picture_path: images/alliance_Step17_window.png
region:
  bottom: 42
  left: 71
  right: 121
  top: 17
swipe: null
threshold: 0.8
window_name: alliance_Step17
