defult_click_point:
  x: 375
  y: 656
method: None
picture_path: images/alliance_Step2_open.png
region:
  bottom: 693
  left: 261
  right: 490
  top: 620
swipe: null
threshold: 0.8
window_name: alliance_Step2
