defult_click_point:
  x: 113
  y: 28
method: check
picture_path: images/alliance_Step2_window.png
region:
  bottom: 40
  left: 67
  right: 160
  top: 16
swipe: null
threshold: 0.8
window_name: alliance_Step2
