defult_click_point:
  x: 143
  y: 299
method: None
picture_path: images/alliance_Step9_open.png
region:
  bottom: 309
  left: 93
  right: 194
  top: 289
swipe: null
threshold: 0.8
window_name: alliance_Step9
