defult_click_point:
  x: 31
  y: 28
method: None
picture_path: images/alliance_Step6_open.png
region:
  bottom: 48
  left: 8
  right: 55
  top: 8
swipe: null
threshold: 0.8
window_name: alliance_Step6
