defult_click_point:
  x: 428
  y: 443
method: find
picture_path: images/alliance_Step8_open.png
region:
  bottom: 462
  left: 379
  right: 477
  top: 424
swipe: null
threshold: 0.8
window_name: alliance_Step8
