defult_click_point:
  x: 377
  y: 468
method: None
picture_path: images/alliance_Step7_open.png
region:
  bottom: 505
  left: 261
  right: 494
  top: 431
swipe: null
threshold: 0.8
window_name: alliance_Step7
