defult_click_point:
  x: 121
  y: 29
method: check
picture_path: images/Alliance_mobilization_Step1_window.png
region:
  bottom: 42
  left: 72
  right: 170
  top: 17
swipe: null
threshold: 0.8
window_name: Alliance_mobilization_Step1
