defult_click_point:
  x: 145
  y: 500
method: None
picture_path: images/alliance_Step13_open.png
region:
  bottom: 539
  left: 24
  right: 266
  top: 461
swipe: null
threshold: 0.8
window_name: alliance_Step13
