defult_click_point:
  x: 269
  y: 905
method: None
picture_path: images/alliance_Step11_open.png
region:
  bottom: 918
  left: 219
  right: 320
  top: 893
swipe: null
threshold: 0.8
window_name: alliance_Step11
