defult_click_point:
  x: 400
  y: 926
method: check
picture_path: images/alliance_Step1_open.png
region:
  bottom: 952
  left: 382
  right: 418
  top: 901
swipe: null
threshold: 0.8
window_name: alliance_Step1
