defult_click_point:
  x: 234
  y: 739
method: find
picture_path: images/alliance_Step3_open.png
region:
  bottom: 752
  left: 217
  right: 251
  top: 726
swipe: null
threshold: 0.8
window_name: alliance_Step3
