defult_click_point:
  x: 402
  y: 498
method: None
picture_path: images/alliance_Step7_open.png
region:
  bottom: 538
  left: 278
  right: 527
  top: 459
swipe: null
threshold: 0.8
window_name: alliance_Step7
