defult_click_point:
  x: 382
  y: 758
method: check
picture_path: images/alliance_Step3_window.png
region:
  bottom: 771
  left: 360
  right: 404
  top: 746
swipe: null
threshold: 0.8
window_name: alliance_Step3
