defult_click_point:
  x: 478
  y: 147
method: None
picture_path: images/alliance_Step5_open.png
region:
  bottom: 158
  left: 468
  right: 489
  top: 137
swipe: null
threshold: 0.8
window_name: alliance_Step5
