defult_click_point:
  x: 271
  y: 920
method: None
picture_path: images/alliance_Step14_open.png
region:
  bottom: 934
  left: 221
  right: 322
  top: 906
swipe: null
threshold: 0.8
window_name: alliance_Step14
