defult_click_point:
  x: 120
  y: 29
method: check
picture_path: images/alliance_Step2_window.png
region:
  bottom: 42
  left: 71
  right: 170
  top: 17
swipe: null
threshold: 0.8
window_name: alliance_Step2
