defult_click_point:
  x: 400
  y: 700
method: None
picture_path: images/alliance_Step2_open.png
region:
  bottom: 739
  left: 278
  right: 522
  top: 661
swipe: null
threshold: 0.8
window_name: alliance_Step2
