defult_click_point:
  x: 499
  y: 116
method: None
picture_path: images/alliance_Step16_open.png
region:
  bottom: 126
  left: 489
  right: 510
  top: 106
swipe: null
threshold: 0.8
window_name: alliance_Step16
