defult_click_point:
  x: 30
  y: 26
method: None
picture_path: images/alliance_Step13_open.png
region:
  bottom: 45
  left: 8
  right: 52
  top: 8
swipe: null
threshold: 0.8
window_name: alliance_Step13
