defult_click_point:
  x: 32
  y: 28
method: None
picture_path: images/alliance_Step17_open.png
region:
  bottom: 48
  left: 8
  right: 56
  top: 8
swipe: null
threshold: 0.8
window_name: alliance_Step17
