defult_click_point:
  x: 253
  y: 852
method: None
picture_path: images/AttackIceBeast_Step2_open.png
region:
  bottom: 880
  left: 143
  right: 363
  top: 825
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step2
