defult_click_point:
  x: 269
  y: 627
method: check
picture_path: images/AttackIceBeast_Step3_window.png
region:
  bottom: 661
  left: 165
  right: 374
  top: 594
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step3
