defult_click_point:
  x: 49
  y: 91
method: None
picture_path: images/AttackIceBeast_Step5_open.png
region:
  bottom: 109
  left: 29
  right: 70
  top: 74
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step5
