defult_click_point:
  x: 269
  y: 909
method: None
picture_path: images/AttackIceBeast_Step2_open.png
region:
  bottom: 938
  left: 152
  right: 387
  top: 880
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step2
