defult_click_point:
  x: 386
  y: 852
method: None
picture_path: images/AttackIceBeast_Step6_open.png
region:
  bottom: 880
  left: 284
  right: 488
  top: 824
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step6
