defult_click_point:
  x: 269
  y: 368
method: None
picture_path: images/AttackIceBeast_Step3_open.png
region:
  bottom: 394
  left: 180
  right: 359
  top: 342
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step3
