defult_click_point:
  x: 184
  y: 685
method: swipe_find
picture_path: images/AttackIceBeast_Step1_open.png
region:
  bottom: 721
  left: 137
  right: 231
  top: 650
swipe:
  duration: 310.0
  end:
    x: 366
    y: 700
  start:
    x: 260
    y: 701
threshold: 0.8
window_name: AttackIceBeast_Step1
