defult_click_point:
  x: 47
  y: 86
method: None
picture_path: images/AttackIceBeast_Step5_open.png
region:
  bottom: 103
  left: 28
  right: 66
  top: 70
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step5
