defult_click_point:
  x: 411
  y: 908
method: check
picture_path: images/AttackIceBeast_Step4_window.png
region:
  bottom: 938
  left: 303
  right: 520
  top: 878
swipe: null
threshold: 0.8
window_name: AttackIceBeast_Step4
