defult_click_point:
  x: 285
  y: 495
method: None
picture_path: images/bow_training_complete_open.png
region:
  bottom: 512
  left: 269
  right: 301
  top: 478
swipe: null
threshold: 0.8
window_name: bow_training_complete
