defult_click_point:
  x: 304
  y: 527
method: None
picture_path: images/bow_training_complete_window.png
region:
  bottom: 546
  left: 287
  right: 321
  top: 509
swipe: null
threshold: 0.8
window_name: bow_training_complete
