defult_click_point:
  x: 449
  y: 239
method: None
picture_path: images/close_button_window.png
region:
  bottom: 251
  left: 438
  right: 461
  top: 227
swipe: null
threshold: 0.8
window_name: close_button
