defult_click_point:
  x: 461
  y: 85
method: find
picture_path: images/close_button_open.png
region:
  bottom: 100
  left: 446
  right: 476
  top: 70
swipe: null
threshold: 0.6
window_name: close_button
