defult_click_point:
  x: 349
  y: 414
method: None
picture_path: images/CloseLeftWindow_open.png
region:
  bottom: 430
  left: 340
  right: 358
  top: 398
swipe: null
threshold: 0.8
window_name: CloseLeftWindow
