defult_click_point:
  x: 479
  y: 254
method: None
picture_path: images/close_button_window.png
region:
  bottom: 267
  left: 467
  right: 491
  top: 242
swipe: null
threshold: 0.8
window_name: close_button
