defult_click_point:
  x: 392
  y: 679
method: swipe_find
picture_path: images/coal_collection_Step2_open.png
region:
  bottom: 715
  left: 347
  right: 437
  top: 643
swipe:
  duration: 440.0
  end:
    x: 117
    y: 700
  start:
    x: 305
    y: 693
threshold: 0.8
window_name: coal_collection_Step2
