defult_click_point:
  x: 392
  y: 683
method: find
picture_path: images/coal_collection_Step2_window.png
region:
  bottom: 720
  left: 347
  right: 437
  top: 647
swipe:
  duration: 440.0
  end:
    x: 117
    y: 700
  start:
    x: 305
    y: 693
threshold: 0.8
window_name: coal_collection_Step2
