defult_click_point:
  x: 24
  y: 234
method: find
picture_path: images/coal_collection_doing_window.png
region:
  bottom: 247
  left: 12
  right: 37
  top: 221
swipe: null
threshold: 0.8
window_name: coal_collection_doing
