defult_click_point:
  x: 461
  y: 240
method: check
picture_path: images/collection_Step6_open.png
region:
  bottom: 257
  left: 445
  right: 478
  top: 224
swipe: null
threshold: 0.4
window_name: collection_Step6
