defult_click_point:
  x: 34
  y: 658
method: None
picture_path: images/collection_Step1_open.png
region:
  bottom: 674
  left: 19
  right: 50
  top: 642
swipe: null
threshold: 0.8
window_name: collection_Step1
