defult_click_point:
  x: 269
  y: 909
method: check
picture_path: images/collection_Step3_open.png
region:
  bottom: 938
  left: 152
  right: 387
  top: 880
swipe: null
threshold: 0.8
window_name: collection_Step3
