defult_click_point:
  x: 411
  y: 907
method: check
picture_path: images/collection_Step7_open.png
region:
  bottom: 937
  left: 303
  right: 520
  top: 878
swipe: null
threshold: 0.8
window_name: collection_Step7
