defult_click_point:
  x: 320
  y: 240
method: check
picture_path: images/collection_Step5_open.png
region:
  bottom: 258
  left: 304
  right: 336
  top: 222
swipe: null
threshold: 0.4
window_name: collection_Step5
