defult_click_point:
  x: 386
  y: 851
method: check
picture_path: images/collection_Step7_open.png
region:
  bottom: 879
  left: 284
  right: 488
  top: 824
swipe: null
threshold: 0.8
window_name: collection_Step7
