defult_click_point:
  x: 89
  y: 27
method: None
picture_path: images/collection_Step4_window.png
region:
  bottom: 39
  left: 67
  right: 112
  top: 16
swipe: null
threshold: 0.8
window_name: collection_Step4
