defult_click_point:
  x: 411
  y: 331
method: check
picture_path: images/collection_Step6_window.png
region:
  bottom: 431
  left: 355
  right: 467
  top: 232
swipe: null
threshold: 0.8
window_name: collection_Step6
