defult_click_point:
  x: 270
  y: 471
method: find
picture_path: images/collection_Step3_window.png
region:
  bottom: 493
  left: 200
  right: 341
  top: 449
swipe: null
threshold: 0.8
window_name: collection_Step3
