defult_click_point:
  x: 32
  y: 501
method: swipe_check
picture_path: images/CXD_open.png
region:
  bottom: 518
  left: 15
  right: 49
  top: 485
swipe:
  duration: 250.0
  end:
    x: 181
    y: 318
  start:
    x: 156
    y: 525
threshold: 0.8
window_name: CXD
