defult_click_point:
  x: 157
  y: 273
method: ocr
picture_path: images/free_quee_1_cool_down.png
region:
  bottom: 285
  left: 125
  right: 189
  top: 261
swipe: null
threshold: 0.8
window_name: free_quee_1
