defult_click_point:
  x: 156
  y: 375
method: ocr
picture_path: images/free_quee_3_cool_down.png
region:
  bottom: 387
  left: 125
  right: 187
  top: 364
swipe: null
threshold: 0.8
window_name: free_quee_3
