defult_click_point:
  x: 157
  y: 273
method: None
picture_path: images/FreeArmyQueue_open.png
region:
  bottom: 280
  left: 136
  right: 178
  top: 266
swipe: null
threshold: 0.8
window_name: FreeArmyQueue
