defult_click_point:
  x: 167
  y: 456
method: check
picture_path: images/free_quee_4_window.png
region:
  bottom: 464
  left: 145
  right: 189
  top: 449
swipe: null
threshold: 0.5
window_name: free_quee_4
