defult_click_point:
  x: 167
  y: 564
method: check
picture_path: images/free_quee_6_window.png
region:
  bottom: 572
  left: 145
  right: 189
  top: 557
swipe: null
threshold: 0.5
window_name: free_quee_6
