defult_click_point:
  x: 167
  y: 400
method: check
picture_path: images/free_quee_3_window.png
region:
  bottom: 408
  left: 145
  right: 189
  top: 393
swipe: null
threshold: 0.5
window_name: free_quee_3
