defult_click_point:
  x: 154
  y: 323
method: ocr
picture_path: images/free_quee_2_cool_down.png
region:
  bottom: 335
  left: 125
  right: 184
  top: 312
swipe: null
threshold: 0.8
window_name: free_quee_2
