defult_click_point:
  x: 167
  y: 346
method: check
picture_path: images/free_quee_2_window.png
region:
  bottom: 354
  left: 146
  right: 189
  top: 339
swipe: null
threshold: 0.5
window_name: free_quee_2
