defult_click_point:
  x: 269
  y: 185
method: check
picture_path: images/HeroRecruit_Step3_window.png
region:
  bottom: 200
  left: 242
  right: 297
  top: 170
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step3
