defult_click_point:
  x: 32
  y: 29
method: None
picture_path: images/HeroRecruit_Step6_open.png
region:
  bottom: 51
  left: 7
  right: 57
  top: 7
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step6
