defult_click_point:
  x: 485
  y: 83
method: check
picture_path: images/HeroRecruit_Step2_window.png
region:
  bottom: 101
  left: 449
  right: 522
  top: 65
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step2
