defult_click_point:
  x: 31
  y: 29
method: check
picture_path: images/HeroRecruit_Step4_window.png
region:
  bottom: 51
  left: 6
  right: 57
  top: 8
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step4
