defult_click_point:
  x: 32
  y: 29
method: check
picture_path: images/HeroRecruit_Step5_window.png
region:
  bottom: 51
  left: 7
  right: 57
  top: 7
swipe: null
threshold: 0.7
window_name: HeroRecruit_Step5
