defult_click_point:
  x: 141
  y: 632
method: find
picture_path: images/HeroRecruit_Step3_open.png
region:
  bottom: 659
  left: 40
  right: 243
  top: 605
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step3
