defult_click_point:
  x: 400
  y: 908
method: check
picture_path: images/HeroRecruit_Step1_window.png
region:
  bottom: 923
  left: 348
  right: 453
  top: 894
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step1
