defult_click_point:
  x: 30
  y: 27
method: check
picture_path: images/HeroRecruit_Step5_window.png
region:
  bottom: 48
  left: 7
  right: 54
  top: 7
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step5
