defult_click_point:
  x: 400
  y: 908
method: None
picture_path: images/HeroRecruit_Step2_open.png
region:
  bottom: 923
  left: 348
  right: 453
  top: 894
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step2
