defult_click_point:
  x: 140
  y: 926
method: check
picture_path: images/HeroRecruit_Step1_open.png
region:
  bottom: 953
  left: 122
  right: 159
  top: 899
swipe: null
threshold: 0.8
window_name: HeroRecruit_Step1
