defult_click_point:
  x: 252
  y: 801
method: check
picture_path: images/Intelligence_adventure_Step4_window.png
region:
  bottom: 810
  left: 184
  right: 321
  top: 793
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step4
