defult_click_point:
  x: 91
  y: 27
method: check
picture_path: images/Intelligence_beast_Step3_window.png
region:
  bottom: 39
  left: 68
  right: 114
  top: 16
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step3
