defult_click_point:
  x: 269
  y: 471
method: None
picture_path: images/Intelligence_adventure_Step3_open.png
region:
  bottom: 497
  left: 180
  right: 359
  top: 445
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step3
