defult_click_point:
  x: 97
  y: 31
method: check
picture_path: images/Intelligence_Step1_window.png
region:
  bottom: 44
  left: 71
  right: 123
  top: 18
swipe: null
threshold: 0.8
window_name: Intelligence_Step1
