defult_click_point:
  x: 253
  y: 656
method: find
picture_path: images/Intelligence_beast_Step2_open.png
region:
  bottom: 687
  left: 151
  right: 355
  top: 625
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step2
