defult_click_point:
  x: 73
  y: 469
method: find
picture_path: images/Intelligence_adventure_Step1_open.png
region:
  bottom: 488
  left: 60
  right: 86
  top: 450
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step1
