defult_click_point:
  x: 267
  y: 343
method: check
picture_path: images/Intelligence_adventure_Step4_window.png
region:
  bottom: 375
  left: 213
  right: 322
  top: 311
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step4
