defult_click_point:
  x: 49
  y: 91
method: None
picture_path: images/Intelligence_beast_Step4_open.png
region:
  bottom: 109
  left: 29
  right: 70
  top: 74
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step4
