defult_click_point:
  x: 497
  y: 648
method: find
picture_path: images/Intelligence_Step1_open.png
region:
  bottom: 667
  left: 478
  right: 516
  top: 629
swipe: null
threshold: 0.8
window_name: Intelligence_Step1
