defult_click_point:
  x: 255
  y: 562
method: find
picture_path: images/Intelligence_rescue_Step1_open.png
region:
  bottom: 578
  left: 243
  right: 268
  top: 546
swipe: null
threshold: 0.8
window_name: Intelligence_rescue_Step1
