defult_click_point:
  x: 269
  y: 699
method: find
picture_path: images/Intelligence_beast_Step2_open.png
region:
  bottom: 732
  left: 161
  right: 378
  top: 666
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step2
