defult_click_point:
  x: 370
  y: 843
method: check
picture_path: images/Intelligence_adventure_Step3_window.png
region:
  bottom: 871
  left: 259
  right: 482
  top: 815
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step3
