defult_click_point:
  x: 395
  y: 899
method: check
picture_path: images/Intelligence_adventure_Step3_window.png
region:
  bottom: 929
  left: 276
  right: 514
  top: 869
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step3
