defult_click_point:
  x: 269
  y: 662
method: find
picture_path: images/Intelligence_rescue_Step2_open.png
region:
  bottom: 695
  left: 161
  right: 378
  top: 629
swipe: null
threshold: 0.8
window_name: Intelligence_rescue_Step2
