defult_click_point:
  x: 233
  y: 587
method: find
picture_path: images/Intelligence_rescue_Step1_open.png
region:
  bottom: 604
  left: 220
  right: 246
  top: 570
swipe: null
threshold: 0.8
window_name: Intelligence_rescue_Step1
