defult_click_point:
  x: 266
  y: 338
method: None
picture_path: images/Intelligence_adventure_Step5_open.png
region:
  bottom: 371
  left: 211
  right: 321
  top: 306
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step5
