defult_click_point:
  x: 306
  y: 543
method: find
picture_path: images/Intelligence_adventure_Step1_open.png
region:
  bottom: 562
  left: 294
  right: 318
  top: 525
swipe: null
threshold: 0.8
window_name: Intelligence_adventure_Step1
