defult_click_point:
  x: 411
  y: 908
method: None
picture_path: images/Intelligence_beast_Step5_open.png
region:
  bottom: 938
  left: 303
  right: 520
  top: 878
swipe: null
threshold: 0.8
window_name: Intelligence_beast_Step5
