defult_click_point:
  x: 446
  y: 641
method: find
picture_path: images/iron_collection_Step2_window.png
region:
  bottom: 676
  left: 403
  right: 489
  top: 606
swipe:
  duration: 460.0
  end:
    x: 157
    y: 647
  start:
    x: 355
    y: 648
threshold: 0.8
window_name: iron_collection_Step2
