defult_click_point:
  x: 475
  y: 683
method: find
picture_path: images/iron_collection_Step2_window.png
region:
  bottom: 721
  left: 430
  right: 521
  top: 646
swipe:
  duration: 460.0
  end:
    x: 167
    y: 690
  start:
    x: 378
    y: 691
threshold: 0.8
window_name: iron_collection_Step2
