defult_click_point:
  x: 32
  y: 366
method: find
picture_path: images/iron_collection_doing_window.png
region:
  bottom: 379
  left: 18
  right: 46
  top: 354
swipe: null
threshold: 0.8
window_name: iron_collection_doing
