defult_click_point:
  x: 150
  y: 593
method: check
picture_path: images/IsCooldown_left_window.png
region:
  bottom: 619
  left: 49
  right: 251
  top: 567
swipe: null
threshold: 0.8
window_name: IsCooldown_left
