defult_click_point:
  x: 21
  y: 224
method: check
picture_path: images/left_window_city_window_config_window.png
region:
  bottom: 235
  left: 10
  right: 33
  top: 214
swipe: null
threshold: 0.8
window_name: left_window_city_window_config
