defult_click_point:
  x: 22
  y: 239
method: check
picture_path: images/left_window_world_window.png
region:
  bottom: 248
  left: 12
  right: 32
  top: 230
swipe: null
threshold: 0.8
window_name: left_window_world
