defult_click_point:
  x: 250
  y: 202
method: None
picture_path: images/left_window_world_open.png
region:
  bottom: 210
  left: 235
  right: 265
  top: 195
swipe: null
threshold: 0.8
window_name: left_window_world
