defult_click_point:
  x: 235
  y: 190
method: check
picture_path: images/left_window_world_window.png
region:
  bottom: 197
  left: 222
  right: 249
  top: 183
swipe: null
threshold: 0.8
window_name: left_window_world
