defult_click_point:
  x: 348
  y: 412
method: check
picture_path: images/left_window_window.png
region:
  bottom: 427
  left: 340
  right: 356
  top: 398
swipe: null
threshold: 0.8
window_name: left_window
