defult_click_point:
  x: 22
  y: 239
method: check
picture_path: images/left_window_city_window.png
region:
  bottom: 250
  left: 10
  right: 35
  top: 228
swipe: null
threshold: 0.8
window_name: left_window_city
