defult_click_point:
  x: 86
  y: 202
method: None
picture_path: images/left_window_city_open.png
region:
  bottom: 210
  left: 71
  right: 102
  top: 195
swipe: null
threshold: 0.8
window_name: left_window_city
