defult_click_point:
  x: 12
  y: 421
method: None
picture_path: images/left_window_open.png
region:
  bottom: 437
  left: 2
  right: 23
  top: 405
swipe:
  duration: 0.5
  end:
    x: 0
    y: 0
  start:
    x: 0
    y: 0
threshold: 0.8
window_name: left_window_open
