defult_click_point:
  x: 301
  y: 682
method: find
picture_path: images/meat_collection_Step2_open.png
region:
  bottom: 722
  left: 255
  right: 348
  top: 643
swipe: null
threshold: 0.8
window_name: meat_collection_Step2
