defult_click_point:
  x: 252
  y: 852
method: check
picture_path: images/meat_collection_Step1_window.png
region:
  bottom: 880
  left: 143
  right: 362
  top: 825
swipe: null
threshold: 0.8
window_name: meat_collection_Step1
