defult_click_point:
  x: 24
  y: 189
method: find
picture_path: images/meat_collection_Step7_window.png
region:
  bottom: 197
  left: 16
  right: 33
  top: 182
swipe: null
threshold: 0.8
window_name: meat_collection_Step7
