defult_click_point:
  x: 31
  y: 262
method: find
picture_path: images/meat_collection_doing_window.png
region:
  bottom: 273
  left: 19
  right: 43
  top: 252
swipe: null
threshold: 0.8
window_name: meat_collection_doing
