defult_click_point:
  x: 419
  y: 782
method: find
picture_path: images/MercenaryPrestige_Step1_open.png
region:
  bottom: 797
  left: 401
  right: 438
  top: 768
swipe: null
threshold: 0.8
window_name: MercenaryPrestige_Step1
