defult_click_point:
  x: 318
  y: 224
method: find
picture_path: images/ped_skill_bull_open.png
region:
  bottom: 274
  left: 268
  right: 369
  top: 175
swipe: null
threshold: 0.8
window_name: ped_skill_bull
