defult_click_point:
  x: 450
  y: 884
method: None
picture_path: images/PedTask_Step3_open.png
region:
  bottom: 927
  left: 393
  right: 507
  top: 842
swipe: null
threshold: 0.8
window_name: PedTask_Step3
