defult_click_point:
  x: 93
  y: 173
method: check
picture_path: images/Refresh_Mobilization_Task_Step2_window.png
region:
  bottom: 189
  left: 31
  right: 155
  top: 158
swipe: null
threshold: 0.8
window_name: Refresh_Mobilization_Task_Step2
