defult_click_point:
  x: 384
  y: 591
method: check
picture_path: images/Refresh_Mobilization_left_Step2_window.png
region:
  bottom: 625
  left: 284
  right: 484
  top: 558
swipe: null
threshold: 0.8
window_name: Refresh_Mobilization_left_Step2
