defult_click_point:
  x: 30
  y: 26
method: check
picture_path: images/return_button_window.png
region:
  bottom: 45
  left: 8
  right: 52
  top: 8
swipe: null
threshold: 0.8
window_name: return_button
