defult_click_point:
  x: 31
  y: 28
method: check
picture_path: images/return_button_window.png
region:
  bottom: 48
  left: 8
  right: 55
  top: 8
swipe: null
threshold: 0.7
window_name: return_button
