defult_click_point:
  x: 284
  y: 393
method: None
picture_path: images/shield_training_complete_open.png
region:
  bottom: 410
  left: 269
  right: 300
  top: 376
swipe: null
threshold: 0.8
window_name: shield_training_complete
