defult_click_point:
  x: 303
  y: 419
method: None
picture_path: images/shield_training_complete_window.png
region:
  bottom: 437
  left: 287
  right: 320
  top: 401
swipe: null
threshold: 0.8
window_name: shield_training_complete
