defult_click_point:
  x: 49
  y: 64
method: check
picture_path: images/stamina_threshold_window.png
region:
  bottom: 69
  left: 44
  right: 54
  top: 60
swipe: null
threshold: 0.9
window_name: stamina_threshold
