defult_click_point:
  x: 36
  y: 65
method: check
picture_path: images/stamina_threshold_window.png
region:
  bottom: 69
  left: 31
  right: 42
  top: 61
swipe: null
threshold: 0.94
window_name: stamina_threshold
