defult_click_point:
  x: 284
  y: 444
method: None
picture_path: images/train_Step0_window.png
region:
  bottom: 459
  left: 269
  right: 299
  top: 430
swipe: null
threshold: 0.8
window_name: train_Step0
