defult_click_point:
  x: 397
  y: 902
method: check
picture_path: images/train_Step3_window.png
region:
  bottom: 934
  left: 278
  right: 516
  top: 871
swipe: null
threshold: 0.8
window_name: train_Step3
