defult_click_point:
  x: 299
  y: 404
method: None
picture_path: images/train_Step1_window.png
region:
  bottom: 443
  left: 256
  right: 343
  top: 366
swipe: null
threshold: 0.8
window_name: train_Step1
