defult_click_point:
  x: 271
  y: 357
method: find
picture_path: images/train_Step1_open.png
region:
  bottom: 395
  left: 261
  right: 282
  top: 319
swipe: null
threshold: 0.8
window_name: train_Step1
