defult_click_point:
  x: 392
  y: 609
method: find
picture_path: images/train_Step2_open.png
region:
  bottom: 638
  left: 366
  right: 419
  top: 581
swipe: null
threshold: 0.8
window_name: train_Step2
