defult_click_point:
  x: 367
  y: 712
method: ocr
picture_path: images/train_Step4_open.png
region:
  bottom: 727
  left: 327
  right: 408
  top: 698
swipe: null
threshold: 0.8
window_name: train_Step4
