defult_click_point:
  x: 372
  y: 846
method: check
picture_path: images/train_Step3_window.png
region:
  bottom: 876
  left: 261
  right: 484
  top: 817
swipe: null
threshold: 0.8
window_name: train_Step3
