defult_click_point:
  x: 270
  y: 785
method: check
picture_path: images/treasure_dispatch_open.png
region:
  bottom: 816
  left: 172
  right: 368
  top: 754
swipe: null
threshold: 0.8
window_name: treasure_dispatch
