defult_click_point:
  x: 51
  y: 406
method: swipe_check
picture_path: images/warehouse_rewards_open.png
region:
  bottom: 440
  left: 4
  right: 98
  top: 372
swipe:
  duration: 500
  end:
    x: 162
    y: 300
  start:
    x: 160
    y: 540
threshold: 0.8
window_name: warehouse_rewards_open
