defult_click_point:
  x: 34
  y: 574
method: swipe_find
picture_path: images/warehouse_open.png
region:
  bottom: 593
  left: 17
  right: 51
  top: 556
swipe:
  duration: 500
  end:
    x: 172
    y: 320
  start:
    x: 170
    y: 576
threshold: 0.89
window_name: warehouse
