defult_click_point:
  x: 269
  y: 406
method: None
picture_path: images/warehouse_rewards_open.png
region:
  bottom: 445
  left: 236
  right: 303
  top: 368
swipe: null
threshold: 0.8
window_name: warehouse_rewards
