defult_click_point:
  x: 256
  y: 805
method: check
picture_path: images/warehouse_rewards_window.png
region:
  bottom: 817
  left: 200
  right: 313
  top: 793
swipe:
  duration: 0.5
  end:
    x: 172
    y: 320
  start:
    x: 170
    y: 576
threshold: 0.6
window_name: warehouse_rewards_window
