defult_click_point:
  x: 115
  y: 519
method: check
picture_path: images/warehouse_window.png
region:
  bottom: 555
  left: 85
  right: 146
  top: 483
swipe: null
threshold: 0.8
window_name: warehouse
