defult_click_point:
  x: 385
  y: 853
method: check
picture_path: images/wood_collection_Step7_open.png
region:
  bottom: 880
  left: 285
  right: 485
  top: 827
swipe: null
threshold: 0.8
window_name: wood_collection
