defult_click_point:
  x: 24
  y: 231
method: find
picture_path: images/wood_collection_doing_window.png
region:
  bottom: 244
  left: 11
  right: 37
  top: 219
swipe: null
threshold: 0.8
window_name: wood_collection_doing
