defult_click_point:
  x: 33
  y: 335
method: find
picture_path: images/wood_collection_doing_window.png
region:
  bottom: 346
  left: 22
  right: 45
  top: 325
swipe: null
threshold: 0.8
window_name: wood_collection_doing
