defult_click_point:
  x: 385
  y: 684
method: swipe_find
picture_path: images/wood_collection_Step2_open.png
region:
  bottom: 723
  left: 340
  right: 430
  top: 646
swipe:
  duration: 520.0
  end:
    x: 137
    y: 685
  start:
    x: 358
    y: 684
threshold: 0.8
window_name: wood_collection_Step2
