defult_click_point:
  x: 254
  y: 442
method: check
picture_path: images/wood_collection_Step4_open.png
region:
  bottom: 464
  left: 188
  right: 320
  top: 421
swipe: null
threshold: 0.8
window_name: wood_collection
