defult_click_point:
  x: 253
  y: 311
method: check
picture_path: images/wood_collection_Step5_window.png
region:
  bottom: 407
  left: 200
  right: 306
  top: 215
swipe: null
threshold: 0.8
window_name: wood_collection
