defult_click_point:
  x: 420
  y: 683
method: None
picture_path: images/wood_collection_Step2_window.png
region:
  bottom: 722
  left: 375
  right: 465
  top: 644
swipe:
  duration: 520.0
  end:
    x: 137
    y: 685
  start:
    x: 358
    y: 684
threshold: 0.8
window_name: wood_collection_Step2
